# 1

In [1]:
# La salida mostrada en cada celda corresponde al ultimo valor calculado
2+2
3*5

15

In [2]:
# Al usar print se muestra independientemente del orden
print(2+2)
print(3*5)

4
15


In [3]:
# No cambia el resultado, ya que la variable a se reinicializa cada vez que se ejecuta la celda
a = 5
a = a + 1
print(a)

6


In [4]:
# El resultado cambia cada vez que se ejecuta la celda, 
# ya que el valor de la variable a se actualiza
a = a+1
print(a)

7


Los corchetes que aparecen a la izquierda de cada celda indican el orden en que fue ejecutada, dada por un numero entero. Si el corchete esta vacio, significa que la celda aun no se ejecuto

# 2

In [5]:
2+2

4

In [6]:
a=2
b=5
a**3

8

In [7]:
16%5 # resto de la division

1

In [8]:
2 * a**2 + 0.5 * b + (a+b) / 2

14.0

# 3

In [9]:
a = True
b = False

In [10]:
a == b # esperado: False

False

In [11]:
a | b # esperado: True

True

In [12]:
a == (not b) # esperado: True

True

# 4

In [13]:
a,b,c = 3,4,2

In [14]:
a > b # False

False

In [15]:
a <= b # True

True

In [16]:
a != b # True

True

In [17]:
a == b # False

False

In [18]:
not (a > b) # True

True

In [19]:
((c>a) or (10*c > b)) and not (b/a > c) # True

True

# 6

In [20]:
s = [1,2,3.0,"hola",7+3]

In [21]:
s,s[0],s[1],s[-1]

([1, 2, 3.0, 'hola', 10], 1, 2, 10)

# 7

In [22]:
import numpy as np

In [23]:
v = np.array([1,2,3])
w = np.array([1.2,7,np.pi])
v,w,v+w

(array([1, 2, 3]),
 array([1.2       , 7.        , 3.14159265]),
 array([2.2       , 9.        , 6.14159265]))

# 8

In [24]:
np.set_printoptions(precision=2, suppress=True)

In [25]:
v = np.array([1,2,np.e,7])
w = np.array([1.2,np.pi,4,5])

In [26]:
print("v+w =", v+w) # Suma coordenada a coordenada
print("v*w =", v*w) # Multiplica coordenada a coordenada

v+w = [ 2.2   5.14  6.72 12.  ]
v*w = [ 1.2   6.28 10.87 35.  ]


In [27]:
for expr in [
    "v", "w", "v+w", "v**2", "v%2", "np.sum(v)", "np.sqrt(w)", "v>3", "w<3.5"
]:
    print(f"{expr:11s} == {eval(expr)}")

v           == [1.   2.   2.72 7.  ]
w           == [1.2  3.14 4.   5.  ]
v+w         == [ 2.2   5.14  6.72 12.  ]
v**2        == [ 1.    4.    7.39 49.  ]
v%2         == [1.   0.   0.72 1.  ]
np.sum(v)   == 12.718281828459045
np.sqrt(w)  == [1.1  1.77 2.   2.24]
v>3         == [False False False  True]
w<3.5       == [ True  True False False]


# 9
- **f-string**: format string, se usa para darle formato especial a un string. Dentro del string, se le puede agregar valores a traves de variables o expresiones entre llaves
- **eval**: evalua la expresion entre parentesis, dada por un string

# 10

In [28]:
(v > 3) | (w < 3.5)

array([ True,  True, False,  True])

In [29]:
(v > 3) & (w < 3.5)

array([False, False, False, False])

# 11

In [30]:
b = np.array([True, False, True])
# Para aplicar negacion logica elemento a elemento en un 
# array de booleanos de numpy, se usa ~
~b

array([False,  True, False])

# 12

In [31]:
v = np.array([1,2,np.e,7])
w = np.array([1.2,np.pi,4,5])
z = np.array([0,1])

In [32]:
v*w # [1.2, 6.28, 10..., 35]

array([ 1.2 ,  6.28, 10.87, 35.  ])

In [33]:
v+2 # Suma 2 a cada elemento

array([3.  , 4.  , 4.72, 9.  ])

In [34]:
v+z # tienen distintos elementos. Puede dar error, o truncar al mas corto

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# 13

In [35]:
v = np.array([1, 2, np.e, 7, 5])

In [36]:
v[0], v[1], v[-1], v[-2]

(np.float64(1.0), np.float64(2.0), np.float64(5.0), np.float64(7.0))

In [37]:
v[[0,3]]

array([1., 7.])

In [38]:
v[0:3], v[0:1]

(array([1.  , 2.  , 2.72]), array([1.]))

# 14

In [39]:
v = np.array([1, 2, np.e, 7, 5])
w = np.array([1,0,2,5,0])

In [40]:
v[v > 2] # Filtro por los elementos de v que son mayores que 2

array([2.72, 7.  , 5.  ])

In [41]:
w != 0

array([ True, False,  True,  True, False])

In [42]:
# Filtro los elementos de v, tales que comparando elemento a elemento
# con w, me quedo con los indices donde w es distinto de cero
# Para hacer esto, v y w tienen que tener igual longitud
v[w != 0]

array([1.  , 2.72, 7.  ])

# 15

In [43]:
A = np.array([[3,2,2],[-1,0,1],[-2,2,4]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[0,1,-1],[5,-2,1]])

In [44]:
A+B

array([[ 4,  2,  2],
       [-1,  1,  1],
       [-2,  2,  5]])

In [45]:
A*B

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 4]])

In [46]:
C**2

array([[ 0,  1,  1],
       [25,  4,  1]])

In [47]:
np.pow(C,2)

array([[ 0,  1,  1],
       [25,  4,  1]])

# 16

In [48]:
A@B

array([[ 3,  2,  2],
       [-1,  0,  1],
       [-2,  2,  4]])

In [49]:
B@C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [50]:
B.shape, C.shape

((3, 3), (2, 3))

In [51]:
B@C.T

array([[ 0,  5],
       [ 1, -2],
       [-1,  1]])

# 17

In [52]:
a = np.sqrt(2)
a

np.float64(1.4142135623730951)

In [53]:
np.round(a)

np.float64(1.0)

In [54]:
np.round(a,2)

np.float64(1.41)

In [55]:
np.info(np.round)

Evenly round to the given number of decimals.

Parameters
----------
a : array_like
    Input data.
decimals : int, optional
    Number of decimal places to round to (default: 0).  If
    decimals is negative, it specifies the number of positions to
    the left of the decimal point.
out : ndarray, optional
    Alternative output array in which to place the result. It must have
    the same shape as the expected output, but the type of the output
    values will be cast if necessary. See :ref:`ufuncs-output-type`
    for more details.

Returns
-------
rounded_array : ndarray
    An array of the same type as `a`, containing the rounded values.
    Unless `out` was specified, a new array is created.  A reference to
    the result is returned.

    The real and imaginary parts of complex numbers are rounded
    separately.  The result of rounding a float is a float.

See Also
--------
ndarray.round : equivalent method
around : an alias for this function
ceil, fix, floor, rint, trunc


Not

In [56]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
``i >= x``.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None

# 18

In [57]:
v = np.array([a, a**2, a**3, a**(.5)])

In [58]:
np.floor(v)

array([1., 2., 2., 1.])

# 19

In [59]:
np.max(v) # Devuelve el maximo del array v

np.float64(2.8284271247461907)

In [60]:
np.min(v) # Devuelve el minimo

np.float64(1.189207115002721)

In [61]:
np.sum(v) # suma de elementos

np.float64(7.431847802122007)

In [62]:
np.mean(v) # valor medio

np.float64(1.8579619505305018)

In [63]:
np.sort(v) # ordena de menor a mayor

array([1.19, 1.41, 2.  , 2.83])

# 20

In [64]:
alturas_cm = np.array([180, 178, 154, 202])
frutas = np.array(["banana", "pera", "durazno"])

In [65]:
np.max(alturas_cm), np.min(alturas_cm), np.sum(alturas_cm), np.mean(alturas_cm), np.sort(alturas_cm)

(np.int64(202),
 np.int64(154),
 np.int64(714),
 np.float64(178.5),
 array([154, 178, 180, 202]))

In [66]:
np.sort(frutas)

array(['banana', 'durazno', 'pera'], dtype='<U7')

# 21

In [67]:
# a)
np.sqrt(np.sum(v**2))

np.float64(3.926093931934525)

In [68]:
# b)
np.sqrt(np.sum((v-w)**2))

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [69]:
# c)
np.sum(v*w)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

# 22

In [70]:
def todosPositivos(v):
    return np.all( v > 0)
    
v0 = np.array ([3 , 4])
v1 = np.array ([3 , 5 , -1 , 1])
for i , v in enumerate([ v0 , v1 ]):
    assert todosPositivos(v) , f"No todos los elementos son positivos en v{i}"

AssertionError: No todos los elementos son positivos en v1

# 23

In [71]:
def norma2(v):
    return np.sqrt(np.sum(v**2))

norma2(v0), norma2(v1)

(np.float64(5.0), np.float64(6.0))

# 24

In [72]:
alturas_cm, np.argmin(alturas_cm) # Busca la posicion del elemento que es minimo

(array([180, 178, 154, 202]), np.int64(2))

In [73]:
alturas_cm, np.argmax(alturas_cm) # Busca la posicion del elemento que es maximo

(array([180, 178, 154, 202]), np.int64(3))

# 25

In [74]:
x = np.array(["cara", "ceca"])
s = np.random.choice(x, size=10) # toma una muestra de 10 elementos de x, con repeticion
print(s)

y = np.array([1,2,3,4,5,6])
t = np.random.choice(y, size=10) # lo mismo de antes, pero con el vector y
print(t)

u = np.random.choice(y, size=4, replace=False) # toma una muestra de 4 elementos, sin repeticion
print(u) 

['ceca' 'ceca' 'ceca' 'cara' 'ceca' 'ceca' 'cara' 'ceca' 'ceca' 'ceca']
[2 3 6 3 5 6 2 5 4 6]
[4 1 5 6]


In [79]:
import random
random.choices(x, k=10) # muestra con repeticion

[np.str_('ceca'),
 np.str_('ceca'),
 np.str_('cara'),
 np.str_('cara'),
 np.str_('cara'),
 np.str_('ceca'),
 np.str_('ceca'),
 np.str_('cara'),
 np.str_('cara'),
 np.str_('cara')]

In [85]:
random.sample([1,2,3,4,5,6,7,8,9], k=5) # muestra con repeticion. La lista tiene que ser una secuencia (lista, etc)

[5, 8, 3, 9, 1]

# 26

In [110]:
moneda = np.array(["cara", "ceca"])

def proporcion_caras(n):
    sample = np.random.choice(moneda, size=n)
    return np.sum(sample == "cara") / sample.size

In [111]:
proporcion_caras(10)

np.float64(0.6)

In [112]:
proporcion_caras(100)

np.float64(0.47)

In [113]:
proporcion_caras(1000)

np.float64(0.495)

In [114]:
proporcion_caras(100000)

np.float64(0.50083)

# 27

In [119]:
# a) 1
sample = np.random.choice(moneda, size=10000)
np.sum(sample == "cara") / np.sum(sample == "ceca")

np.float64(0.958096729978461)

In [123]:
# b) indeterminado
sample = np.random.choice(moneda, size=10000)
np.sum(sample == "cara") - np.sum(sample == "ceca")

np.int64(40)

In [126]:
# c) 0
sample = np.random.choice(moneda, size=10000)
(np.sum(sample == "cara") - np.sum(sample == "ceca")) / sample.size

np.float64(0.009)

In [175]:
# d) 0.5
sample = np.random.choice(moneda, size=10000)
# sample

triple_cara_luego_cara = (sample[:-4] == "cara") & (sample[1:-3] == "cara") & (sample[2:-2] == "cara") & (sample[3:-1] == "cara")
# triple_cara_luego_cara

triple_cara_luego_ceca = (sample[:-4] == "cara") & (sample[1:-3] == "cara") & (sample[2:-2] == "cara") & (sample[3:-1] == "ceca")
# triple_cara_luego_ceca

triple_cara_luego_cara.sum() / (triple_cara_luego_cara.sum() + triple_cara_luego_ceca.sum())

np.float64(0.48848292295472595)