In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Python y Jupyter notebook
**Jupyter notebook** permite combinar código Python (celdas Code) con texto con formato y fórmulas matemáticas en Latex (celdas Markdown). Vamos a usar frecuentemente Jupyter notebook en las clases.

Pueden utilizar Jupyter notebook offline desde Anaconda (u otros) o alguna herramienta online, como Google Colab.

Para hacer las prácticas pueden usar Jupyter notebook o cualquier otro entorno.


In [5]:
# Ejemplo de código
2 + 3 * 5

17

In [ ]:
# Podemos ingresar varias instrucciones en la misma celda
a = 5
a

In [ ]:
# Si ejecutamos varios comandos en una misma celda solo se muestra la última salida
b = 3.14
b
b * 2

In [ ]:
# Podemos usar display o print para ver varias salidas
c = "hola"
print(c)
print(a)

### Orden de ejecución
Para ejecutar el contenido de una celta usamos SHIFT+Enter.
Los comandos dentro de la celda se ejecutan en orden.

Si abrimos un Notebook con varias celdas con código, el contenido de esas celdas no se ejecuta hasta que lo hagamos nosotros (podemos hacerlo celda por celda o ejecutar todas automaticamente utilizando "Cell" --> "Run all".

Ejecutar la primer celda, luego la siguiente y luego nuevamente la primera y ver qué sucede.

In [ ]:
print(z)

In [ ]:
z = 10 + 10

**Pregunta:** ¿Qué son los corchetes que aparecen al lado de cada celda de código?

Ejecutar la primera celda dos veces y luego la siguiente celda dos veces. ¿Qué sucede en cada caso? ¿Por qué?

In [ ]:
x = 5
x = x * 2
print(x)

In [ ]:
x = x * 2
print(x * 5)

**Consejo:** Si entregan código en Jupyter Notebook verifiquen siempre que se pueden ejecutar las celdas en orden de arriba hacia abajo.

### Funciones matemáticas

In [6]:
a = 5
b = 3.14
a * b # Producto

15.700000000000001

Aparece el resultado exacto? A qué se debe el error?

In [ ]:
print(a**3) # Potencia

In [ ]:
print(a % 2) # ¿Qué hace?

In [ ]:
print(b % 2) # ¿Qué hace?

In [ ]:
help('%')

In [ ]:
### Tipos de datos
type(a)

In [ ]:
type(b)

In [ ]:
### Las funciones de Python pueden llamarse con variables de distinto tipo, y se comportan distinto según el tipo de dato
d = 5.0
type(d)

In [ ]:
a**100

In [ ]:
d**100

In [ ]:
b**100

In [ ]:
c

In [ ]:
type(c)

In [ ]:
c*2

### Variables booleanas y funciones lógicas
En Python podemos usar variables booleanas True y False, y operadores lógicos: == (igualdad), or, and, not.

In [ ]:
a = True
b = False
print(a == b)
print(a or b)
print(a and b)
print(a == (not b))

In [ ]:
not(b)

El operador de igualdad aplicado a variables numércias compara solo el valor, no el tipo de dato.

In [ ]:
x1 = 5.0
x2 = 7.0
x3 = 12.0
n1 = 5
print(x1+x2 == x3)
print(x1 == 5)
print(x1 == n1)

In [ ]:
type(x1) == type(n1)

In [ ]:
type(x1) == type(x2)

### Listas
Las listas permiten guardar valores de distintos tipos en forma ordenada y acceder a
los distintos elementos por su índice, comenzando desde 0.

In [ ]:
s = [1, 2, 3.0, "hola", 7 + 3]
s

In [ ]:
print(s[0])
print(s[1])
print(s[-1]) # Qué hace esto?

Podemos indicar también un rango de elementos de la lista.

In [ ]:
s[1:3] # ¿Qué nos devuelve? ¿Por qué?

# Numpy

Para trabajar en Python con vectores (y en general para todo tipo de operaciones
matemáticas) vamos a usar el paquete `numpy` . Para eso importamos primero la biblioteca `numpy`
y definimos vectores con el comando `np.array`. 

**Vectores.** Los vectores (o arrays) de numpy son similares a las listas, pero todos los elementos son del mismo tipo (enteros, floats, ...)

Ejecutar el siguiente código y observar los resultados.

In [ ]:
import numpy as np
v = np.array([1,2,3])
w = np.array([1.2, 7, np.pi])
print(v)
print(w)
print(v + w)

In [ ]:
# El tipo de dato de un array de numpy es ndarray
print(type(v))
print(type(w))

In [ ]:
# Si queremos saber el tipo de dato de los elementos del array, usamos dtype
print(v.dtype)
print(w.dtype)

(dtype es un método del objeto ndarray, por eso usamos la escritura v.dtype y no dtype(v))

### La magia de Numpy. 
La biblioteca Numpy reproduce muchas funcionalidades de Matlab.
La mayoría de las operaciones con vectores de Numpy se hacen coordenada a coordenada. Esto permite en muchos casos evitar usar ciclos o ciclos anidados y realizarlos con un solo comando. 

La diferencia de tiempo de ejecución entre utilizar operaciones apropiadas de Numpy o hacerlo mediante ciclos puede ser muy grande.

Ejecutar los siguientes comandos e interpretar los resultados.

In [ ]:
v = np.array([1,2,np.e,7])
w = np.array([1.2, np.pi, 4, 5])
print("v = ", v)
print("w = ", w)
print("v + w = ", v + w)

In [ ]:
print ("v**2 = ", v**2)
print ("v%2 = ", v%2)

In [ ]:
print ("v > 3?", v > 3)
print ("w < 3.5?", w < 3.5)

Algunas funciones de numpy pueden usarse también como métodos

In [ ]:
print(v.sum())
print(np.sum(v))

Las operaciones lógicas or y and no se pueden aplicar a vectores. Debemos usar los símbolos |
(or) y & (and).

In [ ]:
print((v > 3) | (w < 3.5))
print((v > 3) & (w < 3.5))

In [ ]:
print((v > 3) or (w < 3.5))
print((v > 3) and (w < 3.5))

**Pregunta:** ¿Cómo podemos negar una variable booleana? ¿Como podemos negar un vector de numpy?

In [ ]:
u = True
v = np.array([True, True, False, True])


Si queremos quedarnos con sólo algunos elementos de un vector, tenemos varias formas de hacerlo.

In [7]:
v = np.array([1, 2, np.e, 7, 5])
v[0], v[1], v[-1]  # Dependiendo la versión de Python puede verse distinta la salida

(np.float64(1.0), np.float64(2.0), np.float64(5.0))

In [8]:
# Print muestra el resultado en forma distinta, más "prolija"
print(v[0], v[1], v[-1])

1.0 2.0 5.0


In [9]:
v[-2] # Qué nos devuelve esto?

np.float64(7.0)

In [10]:
v[[0, 3]] # Qué nos devuelve esto?

array([1., 7.])

In [11]:
# Ojo, no podemos hacer lo mismo con listas
s = [1, 2, 3.0, "hola", 7 + 3]
s[[0,3]]

TypeError: list indices must be integers or slices, not list

In [12]:
# También podemos usar rangos
v[0:3]

array([1.        , 2.        , 2.71828183])

Y podemos seleccionar los elementos que cumplan alguna propiedad.

In [ ]:
v = np.array([1, 2, np.e, 7, 5])
w = np.array([1, 0, 2, 5, 0])
print(w>2)
v[w > 2]

**Ejercicio**
1. Definir un vector $v$ con los números enteros del 0 al 15 (ambos incluidos) utilizando np.arange()
2. A partir de $v$, definir un vector $w$ con los primeros 16 numeros pares (comenzando en 0).
3. A partir de $w$, definir un vector $x$ con los primeros 16 numeros impares (comenzando en 1).
4. Definir un vector $y$ que tenga solo los múltiplo de 3 en $x$.
5. Calcular la suma de los primeros 16 números impares y la suma de los primeros 16 cuadrados perfectos (comenzando en 0)

In [15]:
# 1
v = np.arange(0, 16)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
# 2
w = v*2
w

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [18]:
# 3
x = w+1
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [20]:
# 4
y = x[x%3 == 0]
y

array([ 3,  9, 15, 21, 27])

In [48]:
# 5
x.sum() + np.sum(v**2)

np.int64(1496)

**Ejercicio** 

Evaluar el polinomio $p(x) = x^3 + 3x^2 + 1$ en todas las coordenadas del vector $(-1, 0, 1, 2, 4)$.


In [50]:
a = np.array([-1,0,1,2,4])
a**3 + 3*a**2 + 1

array([  3,   1,   5,  21, 113])

**Ejercicio.**
Utilizando solo las operaciones y funciones vistas en los ejercicios anteriores, escribir un código
de una sola línea para la función matemática:

$$\langle v, w\rangle = v_1 \cdot w_1 + v_2 \cdot w_2 + \dots + v_n \cdot w_n = \sum_{i=1}^n v_i \cdot w_i$$

In [52]:
v = np.array([1,0,2,7])
w = np.array([1,2,3,4])
np.sum(v*w)

np.int64(35)

**Matrices.** Las matrices se definen en numpy como arrays de filas. Las operaciones usuales
se realizan coordenada a coordenada al igual que con vectores. Verificar los resultados de los
siguientes comandos.

In [53]:
A = np.array([[3, 2, 2], [-1, 0, 1], [-2, 2, 5]])
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
C = np.array([[0, 1, -1], [5, -2, 1]])
A + B

array([[ 4,  2,  2],
       [-1,  1,  1],
       [-2,  2,  6]])

In [54]:
A

array([[ 3,  2,  2],
       [-1,  0,  1],
       [-2,  2,  5]])

In [55]:
print(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [56]:
A * B

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 5]])

In [57]:
C**2

array([[ 0,  1,  1],
       [25,  4,  1]])

El producto usual de matrices se realiza con el comando @ . 

A.T es la transpuesta de A. 

Verificar los resultados de los siguientes comandos.

In [58]:
C>2

array([[False, False, False],
       [ True, False, False]])

In [59]:
A @ B

array([[ 3,  2,  2],
       [-1,  0,  1],
       [-2,  2,  5]])

In [60]:
B @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [61]:
B.shape, C.shape

((3, 3), (2, 3))

In [62]:
B @ C.T

array([[ 0,  5],
       [ 1, -2],
       [-1,  1]])

**Ejercicio** 

Evaluar el polinomio $p(x) = x^3 + 3x^2 + 1$ en todas las coordenadas de la matriz 
$$
\begin{pmatrix}
0 & -1 & -2 \\
-2 & 3 & 1
\end{pmatrix}
$$


In [64]:
M = np.array([[0,-1,-2],[-2,3,1]])
M**3 + 3*M**2 + 1

array([[ 1,  3,  5],
       [ 5, 55,  5]])

## Funciones

Las funciones son bloques de código organizado que se usan para realizar tares específicas.

Reciben un input (un número o una variable, por ejemplo) y devuelven un output. Los inputs van
entre paréntesis y separados por una coma, si hay más de uno. 

Muchas funciones están disponibles en la biblioteca estándar de Python, otras estás agrupadas en distintas bibliotecas, como numpy que agrupa una gran cantidad de funciones matemáticas. 

El objetivo de estos ejercicios es familiarizarse con varias funciones básicas de Python.

Ejecutar estas operaciones en la consola para entender qué hacen las funciones de numpy.

In [ ]:
a = np.sqrt(2)
a

In [ ]:
np.round(a)

In [ ]:
np.round(a, 2)

In [13]:
help(np.round)

Help on _ArrayFunctionDispatcher in module numpy:

round(a, decimals=0, out=None)
    Evenly round to the given number of decimals.

    Parameters
    ----------
    a : array_like
        Input data.
    decimals : int, optional
        Number of decimal places to round to (default: 0).  If
        decimals is negative, it specifies the number of positions to
        the left of the decimal point.
    out : ndarray, optional
        Alternative output array in which to place the result. It must have
        the same shape as the expected output, but the type of the output
        values will be cast if necessary. See :ref:`ufuncs-output-type`
        for more details.

    Returns
    -------
    rounded_array : ndarray
        An array of the same type as `a`, containing the rounded values.
        Unless `out` was specified, a new array is created.  A reference to
        the result is returned.

        The real and imaginary parts of complex numbers are rounded
        separately

In [14]:
# Para las funciones de numpy, también podemos ver información con np.info
np.info(np.round)

Evenly round to the given number of decimals.

Parameters
----------
a : array_like
    Input data.
decimals : int, optional
    Number of decimal places to round to (default: 0).  If
    decimals is negative, it specifies the number of positions to
    the left of the decimal point.
out : ndarray, optional
    Alternative output array in which to place the result. It must have
    the same shape as the expected output, but the type of the output
    values will be cast if necessary. See :ref:`ufuncs-output-type`
    for more details.

Returns
-------
rounded_array : ndarray
    An array of the same type as `a`, containing the rounded values.
    Unless `out` was specified, a new array is created.  A reference to
    the result is returned.

    The real and imaginary parts of complex numbers are rounded
    separately.  The result of rounding a float is a float.

See Also
--------
ndarray.round : equivalent method
around : an alias for this function
ceil, fix, floor, rint, trunc


Not

Muchas funciones de numpy se pueden aplicar también en arrays.

In [ ]:
a = np.sqrt(2)
v = np.array([a, a**2, a**3, a**(.5)])
v

In [ ]:
np.floor(v)

**Ejercicio:** Explorar las funciones np.max() , np.min() , np.mean() y np.sort() aplicadas al vector
v del ejercicio anterior. ¿Qué hace cada una?

En Python podemos definir nuestras propias funciones utilizando `def`. 

¿Qué hace la siguiente función? 

¿Qué resultados esperan al aplicar la función a los vectores $v_0$ y $v_1$?

In [ ]:
def positivo(v):
    return np.all(v > 0)

v0 = np.array([3, 4])
v1 = np.array([3, 5, -1, 1])

In [ ]:
print(positivo(v0))

In [ ]:
positivos(v1)

In [ ]:
v1 > 0

**Ejercicio.** Definir una función que calcule la norma-2 de un vector y verificarla en los vectores $v_0$ y $v_1$ del ejercicio anterior.

In [16]:
def norma2(v):
    return np.sqrt(np.sum(v**2))

In [17]:
v0 = np.array([1,2,3])
norma2(v0)

np.float64(3.7416573867739413)

## Azar y simulaciones

Reproducir estos usos de la función np.random.choice() e interpretar qué hace.

In [18]:
x = np.array(["cara", "ceca"])
np.random.choice(x, size=10)

array(['cara', 'cara', 'cara', 'ceca', 'ceca', 'cara', 'ceca', 'ceca',
       'ceca', 'cara'], dtype='<U4')

In [19]:
y = np.array([1,2,3,4,5,6])
np.random.choice(y, size=10)

array([1, 5, 4, 1, 5, 2, 3, 3, 4, 2])

In [20]:
np.random.choice(y, size=4, replace=False)

array([6, 4, 2, 1])

In [21]:
# Funcionará?
np.random.choice(y, size=10, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

**Ley de los grandes números.** Esta ley asegura que si tiramos $n$ veces una moneda, el promedio de veces que sale cara tiende a $1/2$ cuando $n$ tiende a infinito.

Simular 10 lanzamientos de una moneda y calcular el promedio de veces que sale cara. Repetir para $n = 1000$ y $n = 100.000$.

In [35]:
n = 1000000
x = np.array(["cara", "ceca"])
tiradas = np.random.choice(x, size=n)
#tiradas

In [36]:
np.sum(tiradas=="cara") / n

np.float64(0.499897)

**Ejercicio.** Se tira $n$ veces una moneda. Intentar predecir, si existen, los siguientes límites cuando $n$ tiene a infinito y verificar la intuición mediante simulaciones.

1. La cantidad de caras dividido por la cantidad de cecas.
2. La cantidad de caras menos la cantidad de cecas
3. La cantidad de caras menos la cantidad de cecas, divido por la cantidad total de tiradas.
4. **(Difícil)** Considerando las veces que salieron tres caras seguidas, el promedio de veces que en la siguiente tirada sale nuevamente cara.


In [37]:
# 1 - Resultado esperado: 1
np.sum(tiradas == "cara") / np.sum(tiradas == "ceca")

np.float64(0.99958808485452)

In [38]:
# 2 - Resultado esperado: indeterminado
np.sum(tiradas == "cara") - np.sum(tiradas == "ceca")

np.int64(-206)

In [39]:
# 3 - Resultado esperado: 0
(np.sum(tiradas == "cara") - np.sum(tiradas == "ceca")) / n

np.float64(-0.000206)

In [42]:
# 4 - Resultado esperado: 0.5
# TODO
np.sum(((tiradas[0:-2] == tiradas[1:-1]) & (tiradas[1:-1] == tiradas[2:])))

np.int64(250494)

Ejercicio. Calcular el valor promedio al tirar n veces un dado.